server:
  port: 8080

mybatis:
  typeAliasesPackage: com.czj.springboot.model
  configLocation: classpath:config/mybatis.xml
  mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.100.111.181:3307/mss?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 37laQcNS
